[package]
name = "libspinner"
build = "make"
repository = "github.com/briandowns/libspinner"
version = "0.2.1" 
description = "C library for adding a spinner/indicator to terminal applications."
authors = ["Brian J. Downs"]

[dependencies]

