[package]
name = "libspinner"
build = "make"
repository = "github.com/briandowns/libspinner"
homepage = ""
version = "0.3.3" 
description = "C library for adding a spinner/indicator to terminal applications."
authors = ["Brian J. Downs"]

[dependencies]

